server:
  port: 9000
spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/demoJavaSpring
   password: 123456
   username: javaSpring
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    